// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRTE0nbaKUE-L7lJw2DEwk2sHQ_QFLe0',
    appId: '1:337664720837:web:34c571c0c782b610f315ac',
    messagingSenderId: '337664720837',
    projectId: 'learnconnectmyself',
    authDomain: 'learnconnectmyself.firebaseapp.com',
    storageBucket: 'learnconnectmyself.firebasestorage.app',
    measurementId: 'G-BJZL4TNE7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1QpT7AQye9MgJDbMPzGkpCdCNK19pC2Y',
    appId: '1:337664720837:android:75dbfccd07c256fdf315ac',
    messagingSenderId: '337664720837',
    projectId: 'learnconnectmyself',
    storageBucket: 'learnconnectmyself.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQDOYpHM1VLsWsOWoNvw4Jdk9KTv-NtA',
    appId: '1:337664720837:ios:cf11052f107c74b7f315ac',
    messagingSenderId: '337664720837',
    projectId: 'learnconnectmyself',
    storageBucket: 'learnconnectmyself.firebasestorage.app',
    iosBundleId: 'com.example.learnconnectmyself',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQRTE0nbaKUE-L7lJw2DEwk2sHQ_QFLe0',
    appId: '1:337664720837:web:f050e2340b87b2a9f315ac',
    messagingSenderId: '337664720837',
    projectId: 'learnconnectmyself',
    authDomain: 'learnconnectmyself.firebaseapp.com',
    storageBucket: 'learnconnectmyself.firebasestorage.app',
    measurementId: 'G-G8L70QXNH8',
  );
}
